Allow for analysis under rebar3_hank
project-fifo/rebar3_lint pull request #37
Opened 2021-07-25 23:29 UTC by paulo-ferraz-oliveira

2021-07-25 23:41 UTC, paulo-ferraz-oliveira commented on .github/workflows/ci.yml
> -        otp_vsn: [20, 21, 22, 23, 24]
`rebar3_hank` is 21+

2021-07-26 05:47 UTC, elbrujohalcon requested changes

2021-07-26 05:47 UTC, elbrujohalcon commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
This should not be necessary. Just adding `-behavior(ct_suite).` to the module should be enough.

2021-07-26 05:53 UTC, paulo-ferraz-oliveira commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
This is under CI; that behaviour is not 21-compatible.

2021-07-26 05:54 UTC, elbrujohalcon commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
What we did (at NextRoll) was to, either…
1. stop checking the project with <23 OTP versions on CI
2. remove `warnings_as_errors` until we could do that ☝🏻

2021-07-26 05:55 UTC, elbrujohalcon commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
I mean… the addition of `-behavior(ct_suite).` _just_ triggers a warning on versions smaller than OTP23, it doesn't _brake_ the code.

2021-07-26 05:57 UTC, elbrujohalcon commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
Worst case scenario, I'm open to something like having a define in rebar.config's `erl_opts` and then…

```erlang
-ifdef(OTP_VERSION_ABOVE_23).
-behavior(ct_suite).
-endif.
```

But my favorite approach would be to just removing CI support for OTP <23.

2021-07-26 10:52 UTC, paulo-ferraz-oliveira commented on test/test_app_SUITE.erl
> +-hank([{unnecessary_function_arguments, [test_app/1]}]).
Pushed.

2021-07-26 10:52 UTC, paulo-ferraz-oliveira commented on rebar.config
> +{minimum_otp_vsn, "21"}.
Because we're using macro `OTP_RELEASE`.

2021-07-26 11:43 UTC, elbrujohalcon requested changes

2021-07-26 11:43 UTC, elbrujohalcon commented on test/test_app_SUITE.erl
> +-endif.
Hank does handle ct suites prior to `24` (when `ct_suite` behavior didn't exist).
I guess the issue is that it's only for _some_ variants of `OTP23` (i.e. it was introduced in… say… `OTP23.2` or something).
In any case… if we _really really_ need to preserve the `-hank(…)` part, it should only be there for `?OTP_RELEASE == 23`.

2021-07-26 14:21 UTC, paulo-ferraz-oliveira commented on test/test_app_SUITE.erl
> +-endif.
Handled.

2021-07-27 05:34 UTC, elbrujohalcon approved these changes

2021-07-27 05:34 UTC, merged